### ISSUE TITLE
Issue regarding esx_policejob

### ISSUE THREAD

**Issue by Parme89** [ESX-Org/esx_license#4]
Can someone please confirm license is broken for policejob. When i deactivate enable licenses in policejob i am able to check people’s id again but as soon as I activate it we have problem with not be able to check people’s id or licenses

**Comment by Parme89** [comment]
Great , then it’s not only me . Well I also haven’t checked , all I know is that I need to have it set to “false” so I can see people’s id, it’s sad cus it’s fun checking if people have drivinglicenses but it’s too broken for that now

**Comment by ElRocaYT** [comment]
You can do it with a SNIPPET from esx_public. https://github.com/ESX-PUBLIC/ESX-Snippet

**Comment by Parme89** [comment]
Yeah saw that ! Is is a another code than the one already in policejob ? Can I have esx_license disabled ?

**Comment by ElPumpo** [comment]
Unrelated
