### ISSUE TITLE
[SOLVED] Call Reference Error

### ISSUE THREAD

**Issue by x0Z3ro0x** [ESX-Org/esx_license#5]
Here is the full error. 

Error running call reference function for resource esx_license: citizen:/scripting/lua/scheduler.lua:351: server/main.lua:73: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:73: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
[ERROR] [MySQL] Check the error above, an error happens when executing the callback from the query : "SELECT * FROM licenses WHERE type = @type {@type=weapon}"

This error occurs when you press E inside the blue circle. However if you choose to purchase the license money is taken and a DB entry created for that user. Yet when you reload the server, even though they have their license still it asks to buy it and will repeat this again and again.

**Comment by x0Z3ro0x** [comment]
[SOLVED] I was able to solve this error myself by doing the following:

first shutdown your server and delete your `cache` and `weashop` folder located in your `cfx-server-data` and `[esx]` folders. In addition drop your `weashop table` in `MySQL`. Then download this:

https://github.com/manups4e/esx_weashops_with_munitions

This is going to replace the standard esx_weashop resource so install it like you did the previous weashop resource. MAKE SURE TO IMPORT THE NEW SQL! Setup the resource as you wish and enjoy!! This solved my errors. Thank you to manups4e for making an awesome resource that works!

**Comment by ElPumpo** [comment]
Emm, you have not imported esx_weapons.sql?

**Comment by x0Z3ro0x** [comment]
Yes I did. Which was why I had to drop my weashop table before importing the new one.
